# Generated by Django 4.0 on 2022-01-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='اعتبار'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(1, 'مرد'), (2, 'زن')], default=1, max_length=2, verbose_name='جنسیت'),
        ),
    ]
