# Generated by Django 4.0 on 2022-01-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کنسرت')),
                ('singer_name', models.CharField(max_length=100, verbose_name='نام خواننده')),
                ('length', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'کنسرت',
                'verbose_name_plural': 'کنسرت ها',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام موقعیت')),
                ('address', models.CharField(max_length=254, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=13, null=True, verbose_name='شماره تماس')),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(verbose_name='ساعت و تاریخ برگزاری کنسرت')),
                ('status', models.CharField(choices=[('start', 'فروش بلیط شروع شده است'), ('end', 'فروش بلیط ختم شده است'), ('cancel', 'فروش بلیط لغو شده است'), ('sales', 'در حال فروش بلیط')], default='sales', max_length=6, verbose_name='حالت فروش بلیط')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.concert')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.location')),
            ],
        ),
    ]
