# Generated by Django 4.0 on 2022-01-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSales', '0002_profile_alter_concert_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='length',
            field=models.PositiveIntegerField(verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام سالن'),
        ),
    ]
