# Generated by Django 4.0 on 2022-01-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSales', '0003_alter_concert_length_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='seat',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد صندلی'),
        ),
    ]
