# Generated by Django 4.0 on 2022-01-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('TicketSales', '0009_alter_time_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile', verbose_name='نام کاربر'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
